### ISSUE TITLE
Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by Rudloff** [jeffisaak/diceware-pass-gen#3]
Hello,

I have built v1.6 from source.
When I launch it on Android 6.0.1, it crashes:
```
05-13 20:14:47.559 28207 28207 E AndroidRuntime: Process: com.aptasystems.dicewarepasswordgenerator, PID: 28207
05-13 20:14:47.559 28207 28207 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aptasystems.dicewarepasswordgenerator/com.aptasystems.dicewarepasswordgenerator.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:150)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at com.aptasystems.dicewarepasswordgenerator.Diceware.<init>(Diceware.java:55)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at com.aptasystems.dicewarepasswordgenerator.ReinholdDiceware.<init>(ReinholdDiceware.java:16)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at com.aptasystems.dicewarepasswordgenerator.MainActivity.setWordlistSource(MainActivity.java:495)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at com.aptasystems.dicewarepasswordgenerator.MainActivity.onCreate(MainActivity.java:201)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6285)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
05-13 20:14:47.559 28207 28207 E AndroidRuntime: 	... 9 more
05-13 20:14:47.561  2125  4351 W ActivityManager:   Force finishing activity com.aptasystems.dicewarepasswordgenerator/.MainActivity
```

**Comment by jeffisaak** [comment]
Hi Pierre,

You've revealed a problem with the french wordlist. I'll be committing a fix shortly.

Thanks!

Jeff
